/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wanghg_bitmaptest_NdkJniUtil */

#ifndef _Included_com_example_wanghg_bitmaptest_NdkJniUtil
#define _Included_com_example_wanghg_bitmaptest_NdkJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wanghg_bitmaptest_NdkJniUtil
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_wanghg_bitmaptest_NdkJniUtil
 * Method:    calAAddB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL calAAddB
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_wanghg_bitmaptest_NdkJniUtil
 * Method:    getRandom
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL getRandom
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
